# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=40)),
                ('pic', models.FileField(upload_to='media/product_pics')),
            ],
            options={
                'verbose_name': 'image_name',
                'verbose_name_plural': 'image_name',
            },
        ),
    ]
